version: "3.9"

services:
  fastapi:
    build:
      context: . # Путь к Dockerfile
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000" # Пробрасываем порт
    env_file: .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: "postgresql+asyncpg://user:password@postgres:5432/mydatabase"
      REDIS_URL: "redis://redis:6379"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      LOG_LEVEL: "info"
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Для доступа к RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
