version: "3.9"

services:
  fastapi:
    image: baklachok/links_and_tasks:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: always

  celery_worker:
    image: baklachok/links_and_tasks:latest
    container_name: celery-worker
    command: celery -A app.core.celery_app worker --loglevel=debug
    env_file: .env
    depends_on:
      - fastapi
      - redis
      - rabbitmq
    restart: always

  celery_beat:
    image: baklachok/links_and_tasks:latest
    container_name: celery-beat
    command: celery -A app.core.celery_app beat --loglevel=debug
    env_file: .env
    depends_on:
      - fastapi
      - redis
      - rabbitmq
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    restart: always

volumes:
  postgres_data:
